# Generated by Django 4.1.5 on 2023-01-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_bio_customuser_country_of_residence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='highest_level_of_education',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
