# Generated by Django 4.1.5 on 2023-01-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_email_customuser_repeat_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='repeat_password',
        ),
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
