# Generated by Django 4.1.5 on 2023-01-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customuser_repeat_password_customuser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='repeat_password',
            field=models.CharField(default='repeatpassword', max_length=200),
            preserve_default=False,
        ),
    ]
