# Generated by Django 4.1.5 on 2023-01-14 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_pledge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pledge',
            old_name='supporters',
            new_name='supporter',
        ),
    ]
