# Generated by Django 4.1.5 on 2023-01-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_rename_amount_pledge_pledge_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='anonymous',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False),
        ),
    ]
