# Generated by Django 4.1.5 on 2023-01-26 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_pledge_anonymous'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='total',
        ),
    ]
