# Generated by Django 4.1.5 on 2023-01-26 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_project_liked_by_alter_project_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='total',
        ),
    ]
